name: Hola Mundo Continuo

on: [push]

jobs:
  bucle-saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar bucle de saludos
        shell: bash
        run: |
          for i in {1..10}
          do
             echo "Hola mundo $i"
             sleep 5
          done
