name: Hola Mundo Workflow

# Define qué evento dispara la acción
on: [push]

jobs:
  saludar-job:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo inicial
        run: echo "¡Hola mundo cruel, se que saldré adelante.
